// Autogenerated Scheme to C++ Code
// File: P3-12.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << listop ("car", Object("(1 2 3 4 5 6 7 )") );
	cout << endl;
	return 0;
}
