// Autogenerated Scheme to C++ Code
// File: P3-17.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << listop ("cdr", Object("((1 2 3 ) (4 5 6 ) 7 )") );
	cout << endl;
	return 0;
}
