// Autogenerated Scheme to C++ Code
// File: P3-11.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << listop ("list", Object(7) );
	cout << endl;
	return 0;
}
