// Autogenerated Scheme to C++ Code
// File: P3-26.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << listop ("append", Object("(1 2 3 )") , Object("(4 5 6 )") );
	cout << endl;
	cout << listop ("append", Object("(1 2 3 )") , Object("()") );
	cout << endl;
	cout << listop ("append", Object("()") , Object("(4 5 6 )") );
	cout << endl;
	cout << listop ("append", Object("()") , Object("()") );
	cout << endl;
	return 0;
}
