(define (main)
	(display (append '(1 2 3) '(4 5 6)))
	(newline)
	(display (append '(1 2 3) '()))
	(newline)
	(display (append '() '(4 5 6)))
	(newline)
	(display (append '() '()))
	(newline)
)

(main)
