// Autogenerated Scheme to C++ Code
// File: P3-24.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << listop ("cons", Object(1) , Object("(4 5 6 )") );
	cout << endl;
	cout << listop ("cons", Object(1) , Object("()") );
	cout << endl;
	cout << listop ("cons", Object("(1 2 )") , Object("(4 5 6 )") );
	cout << endl;
	cout << listop ("cons", Object("(1 2 3 )") , Object("()") );
	cout << endl;
	cout << listop ("cons", Object("()") , Object("(4 5 6 )") );
	cout << endl;
	return 0;
}
