// Autogenerated Scheme to C++ Code
// File: P3-22.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << listop ("cons", Object(1) , Object("()") );
	cout << endl;
	return 0;
}
