(define (main)
	(display (cons 1 '(4 5 6)))
	(newline)
	(display (cons 1 '()))
	(newline)
	(display (cons '(1 2) '(4 5 6)))
	(newline)
	(display (cons '(1 2 3) '()))
	(newline)
	(display (cons '() '(4 5 6)))
	(newline)
)

(main)
