// Autogenerated Scheme to C++ Code
// File: P3-3.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << Object("(a )") ;
	cout << endl;
	return 0;
}
