// Autogenerated Scheme to C++ Code
// File: P3-38.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << (Object(6)  * Object(3)  * Object(-2)  * Object(5) );
	cout << endl;
	cout << (Object(6.4)  * Object(3.23)  * Object(-2.6)  * Object(5.0) );
	cout << endl;
	return 0;
}
