// Autogenerated Scheme to C++ Code
// File: P3-39.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << ((Object(6)  * Object(3)  * Object(-2)  * Object(5) ) + (Object(3)  - Object(-2) ) + (Object(18)  / Object(6) ));
	cout << endl;
	cout << ((Object(6.4)  * Object(3.23)  * Object(-2.1)  * Object(.05) ) + (Object(36)  - Object(-2) ) + (Object(18.3)  / Object(6) ));
	cout << endl;
	return 0;
}
