// Autogenerated Scheme to C++ Code
// File: P3-45.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object function1 (Object V1, Object V2)
{
	Object __RetVal;
;
	cout << (V1 + V2);
	cout << endl;
	cout << (Object(4.1)  + Object(2.5) );
	cout << endl;
	return __RetVal;
}

Object function2 (Object V1, Object V2)
{
	Object __RetVal;
;
	cout << (V1 - V2);
	cout << endl;
	cout << (V2 - V1);
	cout << endl;
	return __RetVal;
}

Object function3 (Object V1, Object V2)
{
	Object __RetVal;
;
	cout << (V1 * V2);
	cout << endl;
	cout << (V2 * V1);
	cout << endl;
	return __RetVal;
}

Object function4 (Object V1, Object V2)
{
	Object __RetVal;
;
	cout << (V1 / V2);
	cout << endl;
	cout << (V2 / V1);
	cout << endl;
	return __RetVal;
}

Object function5 (Object V1, Object V2)
{
	Object __RetVal;
;
	cout << (V1 % V2);
	cout << endl;
	cout << (V2 % V1);
	cout << endl;
	return __RetVal;
}

int main ()
{
	Object __RetVal;
;
	__RetVal = function1(Object(6)  , Object(3) );
	__RetVal = function2(Object(6)  , Object(3) );
	__RetVal = function3(Object(6)  , Object(3) );
	__RetVal = function4(Object(6)  , Object(3) );
	__RetVal = function5(Object(6)  , Object(3) );
	return 0;
}
