// Autogenerated Scheme to C++ Code
// File: P3-47.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object function1 (Object V)
{
	Object __RetVal;
;
	__RetVal = (Object(5)  + V);
	return __RetVal;
}

int main ()
{
	Object __RetVal;
;
	cout << function1(Object(3) );
	cout << endl;
	return 0;
}
