// Autogenerated Scheme to C++ Code
// File: P3-41.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object function1 ()
{
	Object __RetVal;
;
	cout << Object(5) ;
	cout << endl;
	return __RetVal;
}

int main ()
{
	Object __RetVal;
;
	__RetVal = function1();
	return 0;
}
