// Autogenerated Scheme to C++ Code
// File: P3-4.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << Object("SSU") ;
	cout << endl;
	return 0;
}
