// Autogenerated Scheme to C++ Code
// File: P3-48.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object function1 (Object V1, Object V2)
{
	Object __RetVal;
;
	__RetVal = (V1 + V2);
	return __RetVal;
}

int main ()
{
	Object __RetVal;
;
	cout << function1(Object(3)  , Object(4.7) );
	cout << endl;
	return 0;
}
