// Autogenerated Scheme to C++ Code
// File: P3-42.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object function1 (Object V)
{
	Object __RetVal;
;
	cout << V;
	cout << endl;
	return __RetVal;
}

int main ()
{
	Object __RetVal;
;
	__RetVal = function1(Object(5) );
	return 0;
}
