// Autogenerated Scheme to C++ Code
// File: P3-44.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object function1 ()
{
	Object __RetVal;
;
	cout << (Object(6)  + Object(3) );
	cout << endl;
	cout << (Object(4.1)  + Object(2.5) );
	cout << endl;
	return __RetVal;
}

Object function2 ()
{
	Object __RetVal;
;
	cout << (Object(6)  - Object(3) );
	cout << endl;
	cout << (Object(4.1)  - Object(2.5) );
	cout << endl;
	return __RetVal;
}

Object function3 ()
{
	Object __RetVal;
;
	cout << (Object(6)  * Object(3) );
	cout << endl;
	cout << (Object(4.1)  * Object(2.5) );
	cout << endl;
	return __RetVal;
}

Object function4 ()
{
	Object __RetVal;
;
	cout << (Object(6)  / Object(3) );
	cout << endl;
	cout << (Object(4.1)  / Object(2.5) );
	cout << endl;
	return __RetVal;
}

Object function5 ()
{
	Object __RetVal;
;
	cout << (Object(6)  % Object(3) );
	cout << endl;
	cout << (Object(14)  % Object(8) );
	cout << endl;
	return __RetVal;
}

int main ()
{
	Object __RetVal;
;
	__RetVal = function1();
	__RetVal = function2();
	__RetVal = function3();
	__RetVal = function4();
	__RetVal = function5();
	return 0;
}
