// Autogenerated Scheme to C++ Code
// File: P3-5.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << Object(5) ;
	cout << endl;
	cout << Object(5.123) ;
	cout << endl;
	cout << Object(-5) ;
	cout << endl;
	return 0;
}
