// Autogenerated Scheme to C++ Code
// File: P3-56.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object sum (Object L)
{
	Object __RetVal;
;
	if (nullp (L))
	{
		__RetVal = Object(0) ;
	}
	else
	{
		__RetVal = (listop ("car", L) + sum(listop ("cdr", L)));
	}
;
	return __RetVal;
}

int main ()
{
	Object __RetVal;
;
	cout << sum(Object("(3 5 )") );
	cout << endl;
	cout << sum(Object("(13 3 4 7 12 5 )") );
	cout << endl;
	return 0;
}
