(define (function1 V1)
	(cond 
		((list? V1) (display "value is a list"))
		((string? V1) (display "value is a string"))
		((not (number? V1)) (display "value is not numeric"))
		((zero? V1) (display "value is 0"))
		((< V1 5) (display "value is less than 5"))
		((and (> V1 4) (< V1 10)) (display "value is between 4 and 10"))
		((or (= V1 10) (= V1 15)) (display "value is 10 or 15"))
		((>= V1 20) (display "value is greater than or equal to 20"))
		((<= V1 -1) (display "value is greater than or equal to -1"))
		(else (display "value is greater than 10 but not 15"))
	)
)

(define (main)
	(function1 3)
	(newline)
	(function1 6)
	(newline)
	(function1 13)
	(newline)
)

(main)
