// Autogenerated Scheme to C++ Code
// File: P3-6.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << Object("a") ;
	cout << endl;
	cout << Object("abc") ;
	cout << endl;
	cout << Object("5") ;
	cout << endl;
	return 0;
}
