// Autogenerated Scheme to C++ Code
// File: P3-7.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << Object("(a )") ;
	cout << endl;
	cout << Object("()") ;
	cout << endl;
	cout << Object("(1 2 3 )") ;
	cout << endl;
	cout << Object("(1 2 3 (a ) 5 6 )") ;
	cout << endl;
	return 0;
}
