// Autogenerated Scheme to C++ Code
// File: P3-8.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << Object("SSU") ;
	cout << endl;
	cout << Object("Hello World") ;
	cout << endl;
	cout << Object("The car of '(1 2 3) is 1") ;
	cout << endl;
	cout << Object("hello 12.3 append if display newline car define number? list? zero? null? string?") ;
	cout << endl;
	cout << Object("+ - / * modulo round = > < >= < = cond else") ;
	cout << endl;
	cout << Object("1 'ac 2 '(and or not)") ;
	cout << endl;
	return 0;
}
