(define (main)
	(display "SSU")
	(newline)
	(display "Hello World")
	(newline)
	(display "The car of '(1 2 3) is 1")
	(newline)
	(display "hello 12.3 append if display newline car define number? list? zero? null? string?")
	(newline)
	(display "+ - / * modulo round = > < >= < = cond else")
	(newline)
	(display "1 'ac 2 '(and or not)")
	(newline)
)

(main)
