// Autogenerated Scheme to C++ Code
// File: P3-9.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
;
	cout << Object(5) ;
	cout << endl;
	cout << Object(5.123) ;
	cout << endl;
	cout << Object(-5) ;
	cout << endl;
	cout << Object("a") ;
	cout << endl;
	cout << Object("abc") ;
	cout << endl;
	cout << Object("5") ;
	cout << endl;
	cout << Object("(a )") ;
	cout << endl;
	cout << Object("()") ;
	cout << endl;
	cout << Object("(1 2 3 )") ;
	cout << endl;
	cout << Object("(1 2 3 (a ) 5 6 )") ;
	cout << endl;
	cout << Object("SSU") ;
	cout << endl;
	cout << Object("Hello World") ;
	cout << endl;
	cout << Object("The car of '(1 2 3) is 1") ;
	cout << endl;
	return 0;
}
